version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=wp_cli_test
      - MARIADB_DATABASE=wp_cli_test
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wp_cli_test
      - WORDPRESS_DATABASE_NAME=wp_cli_test
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  wordpress_data:
    driver: local